### ISSUE TITLE
Bug : Unchecking 'Show in menu' for a page doesn't work

### ISSUE THREAD

**Issue by N07070** [anchorcms/anchor-cms#1123] opened 2016-07-07 09:30 UTC
### Summary

When on a page, created to write something, you can uncheck the 'Show in menu button', but upon visiting the website, it's still in the menu. Of course, the page was saved, etc...

### Expected Behaviour

- Be on a page, separate from posts
- Write anything you want in the post, 
- Uncheck the 'show in menu checkbox',
- Save the article,
- Publish it, 
- The link to the article doesn't appear in the menu on the front page

### Actual Behaviour

- The link to the article appears in the menu.

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: Debian Jessie, up to date
- URL : http://n07070.xyz

**Comment by daviddarnes** [comment] 2016-07-07 09:41
Duplicate of https://github.com/anchorcms/anchor-cms/issues/1063

**Closed by daviddarnes** 2016-07-07 09:41 UTC
Labels: Bug, Medium Priority
