### ISSUE TITLE
No text in posts after upgrade

### ISSUE THREAD

**Issue by agodlydeciple** [anchorcms/anchor-cms#1016] opened 2016-02-26 19:01 UTC
### Summary

When trying to edit previous posts after upgrading to 0.9.2 to 0.12 there is no text in the text area. Just the 'Just Write' prompt.  
![image](https://cloud.githubusercontent.com/assets/683837/13362274/f9629c10-dc88-11e5-9b48-0bb5cebb940a.png)

The Text that is in the posts shows on the actual website, but you can't edit them.
![image](https://cloud.githubusercontent.com/assets/683837/13362282/04109202-dc89-11e5-8211-97721fe0ae03.png)

### Expected Behaviour

- Open Post to Edit
- Form shows current post text
- Edit post
- Save new post

### Actual Behaviour

- Open Post to Edit
- Current text in post not there. 
- Can't edit post

### Context details (if applicable)

- Anchor version: 0.12
- Server setup: Cent OS 7, PHP 7

**Comment by daviddarnes** [comment] 2016-02-26 19:31
Oh now this does sound similar to my issue yesterday. Is this a test setup?

If it is a test setup, can you try turning on comments on that post and try saving again? Don't do this if this if it's a live project!

**Comment by agodlydeciple** [comment] 2016-02-26 19:33
It's a semi-live project.  It's a personal blog that I have in the process of using and what not. I am sure I am the only one that is using/reading it so it shouldn't be that big of a deal. 

Are there any ramifications to what you're suggesting?

**Comment by CraigChilds94** [comment] 2016-02-26 19:47
@daviddarnes it does sound familiar;) 

I know a fix for this. I'll push it up soon

**Comment by CraigChilds94** [comment] 2016-02-26 19:48
@agodlydeciple can you please paste the contents of your anchor error log file?

**Comment by agodlydeciple** [comment] 2016-02-26 19:52
I would however there doesn't seem to be any anchor error file. I am looking in the projects root folder and there isn't anything there.

**Comment by CraigChilds94** [comment] 2016-02-26 20:00
the log would be in `anchor/errors.log`

**Comment by CraigChilds94** [comment] 2016-02-26 20:03
@agodlydeciple I'm going to set myself up a 0.9.2 version and then upgrade to see if I can replicate your issue and come up with a solution. The solution will most likely be in the form of another release as a patch to fix the issue

**Comment by agodlydeciple** [comment] 2016-02-26 20:06
@CraigChilds94 Ah - sorry yes it is there. The only thing in my errors.log file is:
```bash
# cat anchor/errors.log
{"date":"2016-02-26 12:09:56","message":"Class 'RandomLib\\Factory' not found","trace":[{"function":"shutdown","class":"System\\Error","type":"::","args":[]}],"line":58,"file":"\/var\/www\/blog\/system\/helpers.php"}
{"date":"2016-02-26 12:10:19","message":"Class 'RandomLib\\Factory' not found","trace":[{"function":"shutdown","class":"System\\Error","type":"::","args":[]}],"line":58,"file":"\/var\/www\/blog\/system\/helpers.php"}
```
Which was the issue fixed by issue #1014 

So no other errors seem to be getting logged.  I await to see if your instance runs into the same issue as myself.

**Comment by CraigChilds94** [comment] 2016-02-26 20:08
@agodlydeciple That's cool, that's helps point it to what I think the issue is. Just using my own test to confirm.

**Comment by CraigChilds94** [comment] 2016-02-26 20:51
@agodlydeciple Replace the contents of `anchor/migrations/211_alter_post_page_content.php` with this:

```
<?php

class Migration_alter_post_page_content extends Migration {

    public function up() {
        $table = Base::table('pages');
        $table2 = Base::table('posts');

        if($this->has_table_column($table, 'content')) {
            $sql  = 'ALTER TABLE `' . $table . '` ';
            $sql .= 'CHANGE `content` `markdown` TEXT';
            DB::ask($sql);
        }

        if(!$this->has_table_column($table, 'html') && $this->has_table_column($table, 'markdown')) {
            $sql  = 'ALTER TABLE `' . $table . '` ';
            $sql .= 'ADD `html` TEXT NOT NULL AFTER `markdown`';
            DB::ask($sql);

            $pages = Page::sort('menu_order', 'desc')->get();
            foreach ($pages as $page) {
                Page::update($page->id, array(
                    'html' => parse($page->markdown)
                ));
            }
        }

        if(!$this->has_table_column($table2, 'markdown') && $this->has_table_column($table2, 'html')) {
            $sql  = 'ALTER TABLE `' . $table2 . '` ';
            $sql .= 'ADD `markdown` TEXT NOT NULL AFTER `description`';
            DB::ask($sql);

            $migrate_data_sql = 'update `' . $table2 . '` set `markdown` = `html`, `html` = "";';
            DB::ask($migrate_data_sql);

            $posts = Post::sort('created', 'desc')->get();
            foreach ($posts as $post) {
                Post::update($post->id, array(
                    'html' => parse($post->markdown)
                ));
            }
        }
    }

    public function down() {}

}
```

then go to your `config/migrations.php` file and change the `migration` number to `211`. That should do the trick.

**Comment by agodlydeciple** [comment] 2016-02-26 21:03
Unfortunately it didn't seem to fix it

migrations.php
```php
cat migrations.php 
<?php

return array(
        /*
         * Latest migration
         */
        'current' => 211
);
```

211_alter_post_page_content.php
```php
<?php

class Migration_alter_post_page_content extends Migration {

    public function up() {
        $table = Base::table('pages');
        $table2 = Base::table('posts');

        if($this->has_table_column($table, 'content')) {
            $sql  = 'ALTER TABLE `' . $table . '` ';
            $sql .= 'CHANGE `content` `markdown` TEXT';
            DB::ask($sql);
        }

        if(!$this->has_table_column($table, 'html') && $this->has_table_column($table, 'markdown')) {
            $sql  = 'ALTER TABLE `' . $table . '` ';
            $sql .= 'ADD `html` TEXT NOT NULL AFTER `markdown`';
            DB::ask($sql);

            $pages = Page::sort('menu_order', 'desc')->get();
            foreach ($pages as $page) {
                Page::update($page->id, array(
                    'html' => parse($page->markdown)
                ));
            }
        }

        if(!$this->has_table_column($table2, 'markdown') && $this->has_table_column($table2, 'html')) {
            $sql  = 'ALTER TABLE `' . $table2 . '` ';
            $sql .= 'ADD `markdown` TEXT NOT NULL AFTER `description`';
            DB::ask($sql);

            $migrate_data_sql = 'update `' . $table2 . '` set `markdown` = `html`, `html` = "";';
            DB::ask($migrate_data_sql);

            $posts = Post::sort('created', 'desc')->get();
            foreach ($posts as $post) {
                Post::update($post->id, array(
                    'html' => parse($post->markdown)
                ));
            }
        }
    }

    public function down() {}

}
```

I changed both files as you stated and nothing changed still see the same window when trying to edit a post:
![image](https://cloud.githubusercontent.com/assets/683837/13365339/03f04d88-dc9a-11e5-85c8-655ddcc335d0.png)

Did I not set something correctly?

**Comment by CraigChilds94** [comment] 2016-02-26 21:07
What the issue is, is that the markdown was moved to the html field and wasn't moved back and re-parsed which is what my script does. Are you sure you altered the current migration number in the database?

**Comment by agodlydeciple** [comment] 2016-02-26 21:08
I didn't alter it in the database your instructions had said to alter the migrations.php file in the config folder which was already set to 211.  Let me check the database.

**Comment by agodlydeciple** [comment] 2016-02-26 21:10
According to the database, the current_migration is set to 211:
![image](https://cloud.githubusercontent.com/assets/683837/13365485/fd3063ec-dc9a-11e5-8d4b-3a84d68f6d14.png)

**Comment by CraigChilds94** [comment] 2016-02-26 21:11
Yeah, set it to less than 211 and refresh. Sorry my bad, I meant to say about the database.

**Comment by agodlydeciple** [comment] 2016-02-26 21:13
set both current_migration in the database and the value in config/migrations.php to 210 - no change.

**Comment by agodlydeciple** [comment] 2016-02-26 21:14
just refreshed my database table and it automatically went back to 211

**Comment by CraigChilds94** [comment] 2016-02-26 21:17
Did that make any difference? 

If possible can you check to see if the `markdown` field on the `anchor_posts` table is populated?

**Comment by agodlydeciple** [comment] 2016-02-26 21:20
It didn't make any noticeable differences from what I could see.

And no - currently my `markdown` field in `anchor_posts` is not populated.

**Comment by CraigChilds94** [comment] 2016-02-26 21:25
@agodlydeciple delete the `markdown` field from the table, then repeat the step above by setting the migration number in the database to `201`. That should resolve the issue. 

Currently the migration doesn't run the block because the markdown field exists. Sorry I was under the impression the migration was unsuccessful.

**Comment by joshvickerson** [comment] 2016-02-26 21:29
I experienced this same issue upgrading from 0.11. Do I need to follow the process you described here to resolve it or can I just install 0.12.1 to correct it?

**Comment by CraigChilds94** [comment] 2016-02-26 21:31
Installing `0.12.1` should fix it, or if it's already migrated to `211` then copy the migration file over and follow the steps above. Basically it was an oversight in the migration which didn't take this into account.

**Comment by joshvickerson** [comment] 2016-02-26 21:39
Updating to 0.12.1 produced this exception. Following the migration procedure above to see if it's resolved but thought you should be aware.

<h4>Uncaught Exception</h4>
Use of undefined constant MIGRATION_NUMBER - assumed 'MIGRATION_NUMBER'

<h4>Origin</h4>
anchor/config/migrations.php on line 8

**Comment by agodlydeciple** [comment] 2016-02-26 21:40
That did the trick! thank you @CraigChilds94

**Comment by CraigChilds94** [comment] 2016-02-26 21:42
@joshvickerson did you copy the `index.php` ? 

Line 27 should read: `define('MIGRATION_NUMBER', 211);`

**Comment by CraigChilds94** [comment] 2016-02-26 21:42
And no problem @agodlydeciple sorry for leading you on a wild goose chase. I just wanted to make sure the problem was what I thought it was.

**Comment by joshvickerson** [comment] 2016-02-26 21:47
There I go skipping steps again... Copied `index.php` and the exception is gone, but my edit post area is still blank.

I also removed the `markdown` column from the database manually before copying `index.php`.

**Comment by CraigChilds94** [comment] 2016-02-26 21:49
@joshvickerson Did you update the migration number in the database also?

Essentially you need to get it to re-run that migration.

**Comment by joshvickerson** [comment] 2016-02-26 22:28
Ah, no I think I missed that part. When I have some more time to look at it again I will do that and report back if there are any other issues.

**Comment by CraigChilds94** [comment] 2016-02-26 22:29
Thanks @joshvickerson for now I shall close this issue :+1:

**Closed by CraigChilds94** 2016-02-26 22:29 UTC
Labels: Bug, Confirmed, High Priority
