### ISSUE TITLE
CSS Disappears from admin pages...

### ISSUE THREAD

**Issue by FinleyCorrigan** [anchorcms/anchor-cms#1265] opened 2018-03-05 09:16 UTC
### Summary

The CSS of the admin panel randomly just decides to disappear completely and you are left with plain HTML. This happened after installing. I logged in to the admin panel, saw the page with CSS, visited the Posts admin page, and the CSS was missing. Then I went to every other page, and the CSS was also now missing from everywhere. 

- Anchor version: 0.12.6
- Server setup: Hostmantis Web Hosting, PHP, MySQL. Installed from Softaculous. 
- URL: https://blog.finleycorrigan.com/admin

**Comment by daviddarnes** [comment] 2018-03-05 09:56
I think this is a duplicate of https://github.com/anchorcms/anchor-cms/issues/1261, with the CSS file being forbidden

**Comment by FinleyCorrigan** [comment] 2018-03-05 10:00
Yes - just looked... go ahead and mark this as a duplicate.

How can I fix this?

**Comment by FinleyCorrigan** [comment] 2018-03-05 10:05
I made the site use version 0.12.3 and everything seems to work fine... so far 👀

**Comment by CraigChilds94** [comment] 2018-03-05 14:20
@FinleyCorrigan Thanks for reporting this dude, but @daviddarnes is correct it's a duplicate. I'm going to prioritise this, the 0.12.6 was updated to include the fix but it appears to not have.

Could you grab a `.zip` of the `master` branch and see if you get the same results?

**Closed by CraigChilds94** 2018-03-05 14:20 UTC
