### ISSUE TITLE
How to stop errors dumping

### ISSUE THREAD

**Issue by Sneffel** [anchorcms/anchor-cms#828] opened 2015-03-11 19:25 UTC
How to stop those messages from appearing?
![6shl7 jpg](https://cloud.githubusercontent.com/assets/9219144/6604968/b2328394-c82c-11e4-9d62-16ce6939996d.png)

You couldn't help me fixin' my problem, so now I'm here askin' fo' STOP those dumb error reports.
thanks. yò

**Comment by daviddarnes** [comment] 2015-03-12 08:47
This is a duplicate of https://github.com/anchorcms/anchor-cms/issues/827 and is also not an issue with Anchor. Could you please ask these questions using the [official forum](http://forums.anchorcms.com/).

**Closed by daviddarnes** 2015-03-12 08:47 UTC

**Comment by Sneffel** [comment] 2015-03-14 20:58
FUCRRK i can't

**Comment by Sneffel** [comment] 2015-03-14 20:59
and the forum doesn't help..!!
I just want to know how to remove *open_basedir* on *.htaccess*...
or how to remove error report

**Comment by protomorph** [comment] 2015-03-15 01:53
Try reading this [What is open_basedir?](https://support.godaddy.com/help/article/1616/what-is-open_basedir?countrysite=uk) or [this](http://php.net/manual/en/ini.core.php), should give you a starting point to finding the problem

**Comment by daviddarnes** [comment] 2015-03-15 10:06
Issue has now moved to the forum http://forums.anchorcms.com/help/just-a-few-questions-favicon-error-display
