### ISSUE TITLE
SQLite support

### ISSUE THREAD

**Issue by joshas** [anchorcms/anchor-cms#1162] opened 2016-11-23 20:53 UTC
pdo_sqlite is listed in system requirements, but I don't see how to setup anchorcms to use SQLite database.

**Comment by daviddarnes** [comment] 2016-11-23 21:59
Hi @joshas, this is a duplicate of https://github.com/anchorcms/anchor-cms/issues/611. Is this in the latest version @rwarasaurus?

**Comment by rwarasaurus** [comment] 2016-11-23 22:24
In the develop branch yes!

**Comment by CraigChilds94** [comment] 2017-02-19 12:37
@joshas The system requirements on the docs were for the wrong version of Anchor, sorry about that. `0.12.*` does not currently support SQLite. But `1.*` will. You can find the in development version at on the `develop` branch :)

**Closed by CraigChilds94** 2017-02-19 12:37 UTC
Labels: Feature, Medium Priority
