### ISSUE TITLE
Scotch Box doesn't wanna install Anchor CMS

### ISSUE THREAD

**Issue by remminator** [anchorcms/anchor-cms#1204] opened 2017-05-31 21:28 UTC
Hello.

I tried installing Anchor CMS on my Scotch Box (vagrant) installation, but it's telling me "Anchor requires the php module GD to be installed."

What do?

**Comment by daviddarnes** [comment] 2017-06-01 07:56
Hi there! Can you please fill in the details of your setup https://github.com/anchorcms/anchor-cms/blob/master/.github/ISSUE_TEMPLATE.md as stated in the guidelines https://github.com/anchorcms/anchor-cms/blob/master/.github/CONTRIBUTING.md#how-to-submit-issues

**Comment by TheBrenny** [comment] 2017-06-01 12:44
Like @daviddarnes has said, you should really follow the template. At present, we have no clue on the context of the situation other than you're working with vagrant to get an install of Anchor working. Realistically, we can't help you without knowing more.

I'm closing this due to the lack of information, but by all means open a new issue that follows the template. Answering the questions such the Server Context, Steps to reproduce, etc. really help us figure out what's going on.

But I think in your case, it's simply something that you need to figure out how to fix. Maybe start by trying to install GD on Scotch Box, or raising an issue on their repository, because I really don't think the issue is on our side...

I hope this helps a little bit...

**Closed by TheBrenny** 2017-06-01 12:44 UTC
Labels: Low Priority, Not-fixing

**Comment by remminator** [comment] 2017-06-01 14:53
Hello again.

Sorry for the confusion. I really should have posted a bit more details and perhaps done some more research :)

I'll ask the fellows over at Scotch Box if they can't help.

Thank you for your patience - love the Anchor CMS btw :)
