### ISSUE TITLE
Incorrect statement on website: "Painfully easy to install"

### ISSUE THREAD

**Issue by robshep** [anchorcms/anchor-cms#1238] opened 2017-12-21 22:21 UTC
> Painfully easy to install
> Used to the ol’ famous five-minute install? Well, get ready for Anchor’s tantalising two-minute install.

### Summary

Installer assumes that a composer command, or shell access is available. It is not mentioned in the requirements, I have neither but have spent a great longer than 2 minutes merely to admit defeat. 

### Expected Behaviour

1. T=0s download 
2. upload
3. extract
4. check perms
5. create database
6. browse to install URI

7. T<120s Begin using AnchorCMS

### Actual Behaviour

1. T=0s download 
2. upload
3. extract
4. check perms
5. create database
6. browse to install URI
7. Bang!
> We were unable to run composer our selves. Please run "composer install" from the command line to install Anchor. If you do not have composer installed please see https://getcomposer.org/
> (Error #127) Here is the output of the command:
> sh: composer: command not found

8. google composer installation from web script, google similar stuff, read a bunch of stackoverflow, read a bunch of forum posts, read a bunch of github tickets describing similar scearios

9. T > 30mins.  Create issue.

Verdict.  AnchorCMS not fit for non-developers. 

### Context details (if applicable)

Similar issues in April 2016 - 18months ago.  

https://github.com/anchorcms/anchor-cms/issues/1020#issuecomment-207163506

> This has come up a lot, and I think someone is going to create a packaged version that doesn't require composer, but until then, you can do the composer install on your local computer and move the whole vendor folder to your installation on your host.
--

Verdict.  AnchorCMS not fit for non-developers. 

- Anchor version: https://github.com/anchorcms/anchor-cms/releases/tag/0.12.3a
- Server setup: Shared hosting, cPanel, PHP 5.6.32, curl, mcrypt, gd, php-mbstring, pdo_mysql, pdo_sqlite, MariaDB: 10.0.33
- URL: N/A

**Comment by robshep** [comment] 2017-12-21 22:26
https://github.com/anchorcms/anchor-site/compare/master...robshep:patch-1

**Comment by South-Paw** [comment] 2017-12-22 06:37
😆 I mean, while I ended up getting it running in the end, I'd agree about the composer stuff.

Hadn't touched PHP in a while, ended up spending an hour or two trying to work out how to use/download work composer on my windows machine. Finally found some site to download composer dependencies before uploading to the site and installing.

Easy fix would be to provide a download with dependencies included as well as without - probably could be achieved with some CI as well?

**Comment by TheDragonRing** [comment] 2017-12-22 07:44
@robshep and @South-Paw I partially agree with you, partially disagree. Please read through my entire message:

I think "Painfully easy to install" is actually fairly accurate. It was easier than some other things I attempted to install, but it was still painful. And it definitely did not take 2 minutes.
"...Anchor’s tantalising two-minute install" is partially true as well. Installing and setting up Anchor itself does take about 2 minutes - it is just installing and setting up all the dependencies for it that take up all that extra time.

Installing it with all dependencies included could maybe be done with a snap (for Linux users). Installing it without access to some sort of terminal or command line... I have no clue how you would go about that.

And as for "Verdict. AnchorCMS not fit for non-developers": yes, you are correct (in my opinion). Anchor is an open-source software on GitHub and it is not meant to be self-installed by people who don't know what they are doing - when I started out attempting to install it I only partially did, it took about 3 days of learning and experimentation to figure out how to do it properly. If you want a quick and free blog without any developer skills (not even that for Anchor, you only need to know your way around a terminal or command line), use one of the many online blog creators or hosts. Just like many other open-source things (E.g. https://www.discourse.org/) self-installing will take some effort.

**Comment by robshep** [comment] 2017-12-22 08:50
@TheDragonRing Surely my comprehensively described experience demonstrates that  "Painfully easy to install" is **NOT** actually fairly accurate.  I've no idea how you can state otherwise.  Especially when it took you: "about 3 days"


If you want to change the marketing text to: "easier than some other things to install" then sure that's a reasonable statement.  I'm happy to make a patch for this change.

At the time I needed a quick blog, very basic, using markdown.  I scanned the options and hastily went for this one, based on the marketing text, and having scanned the requirements.

When you write this stuff on a website, commercial or open source, people will take your word for it. I literally took the 2 minutes stuff to be true.  Why make a point of comparing to other, more difficult five minute solutions!   That was exactly what I wanted right?  Literally two minutes from now, i'll be dumping my content in, I thought.....

The documentation makes no mention of requiring composer, or needing CLI access in some circumstances.   If that had been listed as a requirement then I would have skipped composer altogether as I have neither on the hosting platform in question.

If your target audience is only developers, (Not sys-admin types) then why bother mentioning how easy it is too install if the user base are supposed to be hacking on the code, or whatever, not simply installing and running it. 

There are plenty of non-developers who have experience running LAMP stack software who will want to check the requirements and follow an install procedure, without wanting to get down and dirty at around the 2:01 mark.  

All three of the commenters on this thread did not achieve the two minute mark.   This proves my point.

**Comment by robshep** [comment] 2017-12-22 08:50
This solves it: https://github.com/anchorcms/anchor-site/pull/20

**Comment by South-Paw** [comment] 2017-12-22 19:43
@robshep While I agree with your issue here, please bear in mind that this is an open source project. People are not (to my knowledge) being paid to work on this and at the end of the day the 'marketing text' that you are seemingly so upset about is minute in the scale of things.

There are plenty of reasonable ways to get this valid criticism solved such as

* Updating documentation to explain that composer is required
* Updating documentation to explain how to use composer
* Updating CI to provide a download with composer dependencies included

When using open source projects, you'll always come across some which make bold claims such as time savings or ease of use but you need to be prepared that some of the time (or most) you'll end up wasting a lot more than claimed - essentially you'd be pretty naive to take marketing text at it's word every time.

It's really annoying and I've been in this place many times as well - but you need to remember that this is open source and you still got it for free - you could have always stopped using it and grabbed another piece of software if it was such an issue.

Every time your respond with a rant as above, you make your issue seem less and less important. This is not me trying to be rude to you - I'm just trying to be honest about it.

The issue is valid in my opinion, so let's try find a valid solution to it - this is not a place for complaints about the project ... it is for issues, bugs and improvements.

**Comment by South-Paw** [comment] 2017-12-22 19:52
Furthermore, it would seem that you're so salty about this issue you've made a PR to delete the entire website and just redirect them to another project...

https://github.com/anchorcms/anchor-site/pull/20

Now I am being a little mean: I think you need to grow up.

**Comment by robshep** [comment] 2017-12-22 19:53
Who's complaining?  or even ranting?  
I'm just having a bit of fun, hence the flippant pull requests, that are clearly tongue in cheek.

I stopped using this at the first hurdle, but figured I would raise this issue (seemingly yet again) for something that is clearly a long standing issue that developers haven't yet addressed.

I've spent more time installing and configuring open source software than I've had hot dinners. (There is a causal relationship there)  
I am more prepared than ever to have my time wasted doing this stuff, but took the 2-minute claim as something that weighed into my decision of which blog engine to install when time was an issue for me. 

The solutions you propose are, naturally, the most obvious, but - having aborted this software and found something more suitable ( picocms.org sub 1-minute by the way) - didn't feel too able to suggest these as I was still suffering from latent untantalisement.

**Comment by South-Paw** [comment] 2017-12-22 19:54
Seems like this issue can be closed then as you're just wanting to waste other peoples time 👍

**Comment by robshep** [comment] 2017-12-22 19:55
quite the opposite.  I don't want other peoples time wasted on the same issue.

**Comment by robshep** [comment] 2017-12-22 19:57
And it seems somebody else ran into it 40 minutes before me.
This issue was self closed - but it's seemingly common.
https://github.com/anchorcms/anchor-cms/issues/1237

**Comment by South-Paw** [comment] 2017-12-22 20:00
I don't have a problem with the issue itself, it seems like valid criticism - it's just the way you're approaching this all is childish 👎

**Comment by robshep** [comment] 2017-12-22 20:02
Just a bit of fun man, lighten up.

**Comment by TheDragonRing** [comment] 2017-12-22 23:34
@robshep obviously you did not read my post properly. I said "Painfully easy" was accurate, because the installation process was:
a) Painful; and
b) Easy

Installing Anchor itself does take me about 2 minutes. It is incredibly easy.
Installing and setting up all of the dependencies for Anchor took me maybe 15-60 minutes.
The 3 days I said were spent in testing out numerous blog softwares, experimenting with them and learning how to install them - only spending limited time on that during the day.

Maybe my last paragraph about the developers was unclear and slightly contradictory, more following my train of thought than my opinion. Let me re-summarize what I had meant to say:
Anchor is open-source, really just a bunch of code on GitHub with some basic installation instructions. Therefore, it will take some degree of knowledge to *self-install* it. Developer knowledge helps (E.g. I used mine to slightly modify some of the CSS of the admin panel to get it to work better on mobile screens), but is not necessary. Really all you need to self-install it is CLI access and knowledge of how to use it.

Using a CLI is not neccessary, however. During those 3 days of testing, the 2 minute install also applied to me for installing it on an online webhost (https://byet.host). Many online webhosts like Byethost and x10Hosting have Softaculous, which installs and sets up everything for you.

Oh, and one other thing? Never assume. Do some research before you attempt to install something. Another tip: When installing something, follow a user-written guide. They're usually more detailed than the one on the project's website (I used this one http://bearfog.com/posts/running-anchor-cms-on-raspberry-pi-2-b).

P.S. You wanted a quick markdown blog? Why not just use Jekyll? There are plenty of Jekyll blog repos you can easily fork and modify.

**Comment by robshep** [comment] 2017-12-23 01:06
Oh come on.  Do you really think those pull requests were serious attempts at "revenge" (snigger) Who in their right mind would even consider merging that rubbish.  

My larkish meanderings have obviously been misinterpreted as spite or something; It is just impish foolery based on the very strong wording to be found on this projects website.

If there weren't such a bold claim, I would have bothered raising the point.  

You guys are being needlessly defensive about such a trivial issue. 

Just patch the docs is all I'm asking.  (Albeit not explicitly, but perhaps I should have been less impish; given that the fanboys might get upset.)  

You'll see that I did very much agree with south-paws suggestions, but you must appreciate by now that resolving this issue (rather than just closing it) won't be for my benefit, it will be to make AnchorCMS easier to install for other people that come along and get stuck at the same place. I would have thought you would care about that more than me?

**Comment by TheDragonRing** [comment] 2017-12-23 01:15
@robshep I know that obviously those were not serious attempts at revenge, but it's still just you fooling around. I agree that the installation guide on the website needs changing, but what I meant by "It could have been valid, but so far it is mostly just you complaining and trying to get your revenge on Anchor for not working for you first try" was that all that fooling around you've been doing will mean that anyone who does have the ability to approve changes to that kind of stuff will look at that fooling around and based on the opinion formed by seeing that will most likely ignore the valid points in this issue and just close it straightaway.

**Comment by robshep** [comment] 2017-12-23 01:20
I doubt that would be the case.

**Comment by TheDragonRing** [comment] 2017-12-23 01:26
You would hope that it wouldn't be, but it is always possible. They may just read your original message, see your pull requests and scroll straight to the bottom to close the issue. That's why it's usually a good idea that if you seriously want something changed, create a serious issue that just states the points that need to be changed, suggest a suitable solution, and leave it at that.

**Comment by South-Paw** [comment] 2017-12-23 19:57
@TheDragonRing I'd dare to say it's more than likely in this case.

Actions, comments and issues like those displayed here (by @robshep) are one of the the reasons for open source software burnout. Lot's of people quit because of people acting like self entitled dicks on the internet when what that dick is getting is free software with a setup time that is minuscule compared to the time it took to develop, test and productionise said software.

I think we all know you (@robshep) were trying to do a little more than 'have some fun' with this issue and the PRs but that is seemingly an easy cover-story to fall back on.

> You guys are being needlessly defensive about such a trivial issue.

You're needlessly being passive-aggressive and awful to random people on an issue thread that you created about what is a *trivial issue* on a *free* open source piece of software.

This issue isn't about the software not working, its not about you loosing your blogs content, its not about you finding a bug, its not about the software being broken - it is simply you complaining about a statement made on the website that you took at face value and want to now complain about and make petty PRs while claiming 'it's just a joke bro, lighten up'.

Project maintainers do look at these issues and they will disregard this issue - funnily enough when it could have been a very valid point that could be easily fixed.

You have burned yourself here and your dismissive arrogance and assumptions (as shown by the way you've interacted on this issue) have burned what I would have assumed to be a good chance that this could have been fixed or changed and definitely without the crud discussion that followed and lead us to this point now.

Surely if I went over to your project and left a comment saying that it doesn't do what it says it does and thus the whole repo should just redirect to a project that does (as you so did with https://github.com/anchorcms/anchor-site/pull/20) then you would get very snotty with me especially if I then on top of that acted the same way you have behaved yourself here.

@CraigChilds94 I think you should just close this issue as the longer it's left open the worse it will get.

I'd also like to question if @robshep has violated the [CODE_OF_CONDUCT](https://github.com/anchorcms/anchor-cms/blob/master/CODE_OF_CONDUCT.md) that was committed on the 14th of November with his PRs/comments that seem to align with what I'd personally consider trolling.

**Comment by daviddarnes** [comment] 2017-12-25 00:53
Howdy all, I just had a read through this thread. I wasn't able to read the entirety as the subject started to drift away from it's original purpose. From what I could see in the initial description is that the installation process of Anchor was not as easy as they expected it to be.

It's been a while since I properly contributed to Anchor, so I decided to install the CMS as fresh myself. Granted that I only did this locally but I was able to get set up quite quickly, the only hurdle I hit was that my php version was out of date (was on v5.4, went to v7.2). I downloaded [v0.12.3 from the releases page](https://github.com/anchorcms/anchor-cms/releases), which is where the website download link takes me too. The release version didn't require composer either, I just downloaded it and ran php in my CLI.

I think it would be worth while making sure people can easily access a "post composer" version though. Maybe potential users are landing on this repo more than on the site? It's something we should be considering at least.

As for the tone of voice used this thread, it's not appreciated. While some see this as humour, most will see this at low jabs at developers providing open source tools to the community for free. The comments a pull requests made in this issue thread to violate our [Code of Conduct](https://github.com/anchorcms/anchor-cms/blob/master/CODE_OF_CONDUCT.md). However in this instance I'm just going to close the issue and hope that no further comments are made. If not then we will have to take further action.

**Closed by daviddarnes** 2017-12-25 00:53 UTC
