### ISSUE TITLE
Markdown is broken on all themes but the default one

### ISSUE THREAD

**Issue by parkervcp** [anchorcms/anchor-cms#1242] opened 2018-01-15 21:56 UTC
### Summary

Markdown is broken on all the themes on https://anchorthemes.com/ 

### Expected Behavior

- Change Theme
- Markdown is rendered in new theme with paragraph structure.

Using "Default" theme
![screen shot 2018-01-15 at 4 54 46 pm](https://user-images.githubusercontent.com/1207679/34963132-e2b20496-fa14-11e7-9c45-d6df0d8ad581.png)

### Actual Behavior

- Change Theme
- Markdown is rendered incorrectly with no paragraph structure

Using the "Vapor" theme
![screen shot 2018-01-15 at 4 55 12 pm](https://user-images.githubusercontent.com/1207679/34963136-e561a0fc-fa14-11e7-90f9-4001db2992f8.png)

### Context details (if applicable)

- Anchor version: 0.12.3
- Server setup: CentOS 7, PHP 7.1, MariaDB 10.1

**Comment by danieljharrin** [comment] 2018-01-18 23:13
Yep, having the same issue too here.

I'm using CloudLinux, PHP 7.2, MariaDB 10.1.24 & LiteSpeed

**Comment by danieljharrin** [comment] 2018-01-18 23:28
I've found something: all themes except default use `<?php echo article_markdown(); ?>` instead of `<?php echo article_html(); ?>` in `article.php`. If you want a quick fix, just replace the markdown version with the html version.

Long term - how is this going to be solved?
- the `article_html()` function should be a direct duplicate of `article_markdown()`. Correct me if I'm wrong here - but they do the same thing.
- all themes need to be updated with the correct code.

**Comment by danieljharrin** [comment] 2018-01-19 06:47
Sure, maybe remove in 1.0 ;)

**Comment by daviddarnes** [comment] 2018-01-19 09:13
@danieljharrin haha, not sure if this is a joke or not but it's actually a good idea. Only drawback is updating all the themes. I'm not sure I'm willing to fork all of them 😩

**Comment by danieljharrin** [comment] 2018-01-19 13:26
@daviddarnes Maybe just create the alias function then. It's up to you.

**Closed** 2018-03-20 14:21 UTC
Labels: Bug, Important

**Comment by warsix4** [comment] 2019-04-25 16:23
I am using 0.12.7 with the Dockyard theme, and even after having changed `article_markdown` to `article_html` I still am not able to get Markdown rendered. Is there multiple locations for article_markdown to show up?
