### ISSUE TITLE
C:\fakepath\   After an image upload only on certain occasions

### ISSUE THREAD

**Issue by unloft** [anchorcms/anchor-cms#1174] opened 2017-01-19 18:43 UTC
### Summary

After an image upload (some times not ever) the system not make a good upload (infact after save i can't see the new image in contetn folder) and add in the path C:\fakepath\"imagename.ext"
### Context details (if applicable)

- Anchor version: last
PROBLEM URL:
http://www.albatrosmagazine.net/coverstory/paolo-conticini

first and second image have this problem but third image all ok :/

**Comment by TheBrenny** [comment] 2017-02-06 04:46
Are you able to give a little bit more detail? I'm unable to reproduce the problem...

**Comment by schmatzler** [comment] 2017-02-15 17:26
I have a similar problem with the latest GIT master. I created a custom article image field. When I upload images under an article, they won't get uploaded.

Image path is replaced with "content", in the database it's inserted as:

    {"name":"content","filename":"content"}

**Comment by schmatzler** [comment] 2017-02-15 19:29
Looked a bit more into it.

The image path getting replaced with "content" is fixed by reverting commit 499e887837d04b843b59709a4b61733abc5f15ff .

Afterwards, I experience the same problem that unloft has. It's actually depending on the browser.

- Uploading with Firefox returns the correct path
- Uploading with Chrome returns C:\Fakepath\file.png

**Comment by unloft** [comment] 2017-02-17 08:17
**TEMPORARILY** I wrote this code for bypass this problem only when appear "fakepath" .


```
<img id="YOUR_CUSTOM_FIELD_NAME"  src="">
<script>
var str="<echo page_custom_field( 'YOUR_CUSTOM_FIELD_NAME' , '' ) >";

if(  str.indexOf("C:\fakepath") > 0 )
{
 var n = str.indexOf("C:\fakepath");
    var str1 = str.substring(0,n);
	var len= str.lenght;
    var str2 = str.substring(19,len);
	document.getElementById("YOUR_CUSTOM_FIELD_NAME").src = str1+str2;
}
	
</script>
```

**Comment by mozzillation** [comment] 2017-02-22 23:01
Hey, I solved the problem by adding this line in `anchor/models/extend.php ` at line `180`

`$image_upload = str_replace( "\\", '/', $image_upload);`

so, the final code is

```
$image_upload = Input::get('extend.' . $extend->key);
  if ($image_upload) {
    $image_upload = str_replace( "\\", '/', $image_upload);
    $filename = basename($image_upload);
    $name = $filename;
  }
```

**Comment by CraigChilds94** [comment] 2017-02-25 12:49
@mozzillation Are you interested in making a PR for this?

**Comment by evansharp** [comment] 2017-03-05 01:33
This should now to closed if the merged fix holds water ;)

**Closed** 2017-03-05 09:54 UTC
Labels: Bug, Unconfirmed

**Comment by frozenpandaman** [comment] 2017-03-13 00:41
Thanks @mozzillation!
