### ISSUE TITLE
Date change resets on refresh

### ISSUE THREAD

**Issue by MattDemers** [anchorcms/anchor-cms#1032] opened 2016-03-07 04:37 UTC
### Summary

When taking a published post and trying to modify its timestamp, it looks like it goes through, but resets on refresh. Only happens with this field; tested whether a post is in draft or published, as well as created before the update and after.

### Expected Behaviour

The new time saved to the post would carry over, and it would affect the sorting of the post on my blog's main page.

### Actual Behaviour

1. Added properly-formatted timestamp on "Published on (GMT):" field.
2. Hit "Save"
3. Refreshed page

### Context details (if applicable)

- Anchor version: 0.12.1
- Server setup: Dreamhost, PHP 5.6
- URL: http://mattdemers.com/blog

**Comment by saucytomato** [comment] 2016-03-07 18:06
Same Issue

**Comment by daviddarnes** [comment] 2016-03-07 18:12
> Damn, I thought I replied to this issue.

Sorry you've both encountered this issue, especially if it's on a live project @MattDemers. Hopefully we can resolve this issue soon.

**Comment by saucytomato** [comment] 2016-03-08 15:29
It doesn't seem to write the new date to the database

**Comment by protomorph** [comment] 2016-03-10 16:21
@saucytomato see if commenting out line 162 in anchor/routes/posts.php, which is `unset($input['created']);` then check if it updates the published time

**Comment by frozenpandaman** [comment] 2016-03-10 16:33
@protomorph That didn't fix it for me.

**Comment by protomorph** [comment] 2016-03-10 17:29
@frozenpandaman OK, I'll dig a bit deeper and see if i can find what the underlying problem is

**Comment by frozenpandaman** [comment] 2016-03-11 08:09
@protomorph Seems to have fixed it—thanks!

**Comment by protomorph** [comment] 2016-03-11 10:19
@frozenpandaman no problem :)

**Comment by CraigChilds94** [comment] 2016-03-11 10:57
I'll have a look at fixing this later for you guys.

**Comment by frozenpandaman** [comment] 2016-03-17 12:03
For some reason, without changing any code/updating anything, this seems to not work anymore. Additionally, the cover image clears whenever trying to change the Published on field (related to issue #1037).

@protomorph @CraigChilds94

**Comment by protomorph** [comment] 2016-03-17 15:04
@frozenpandaman I'll see if I can find a fix

**Comment by saucytomato** [comment] 2016-03-17 15:55
There also seems to be an issue with custom site metadata changing on refresh: probably related

**Comment by protomorph** [comment] 2016-03-17 16:06
@saucytomato What field/fields are changing on refresh? Also, do you have any custom fields?

**Comment by saucytomato** [comment] 2016-03-17 16:51
I'm sorry: I meant the custom site variables aren't saving for me

**Comment by protomorph** [comment] 2016-03-17 17:51
I can't see any reason why it's doing that. Is there a value if you save the variable then go back to the variables listings page?

**Comment by saucytomato** [comment] 2016-03-17 19:06
you can create them and delete them, but can't update them

**Comment by protomorph** [comment] 2016-03-17 19:35
@saucytomato maybe you should start a new issue outlining this problem. Looks like a possible bug. But I'll keep digging to see if I can find the cause of it.

**Comment by frozenpandaman** [comment] 2016-03-18 09:13
@saucytomato @protomorph I have this issue as well. It doesn't give an error – it says "Your variable was updated" – but nothing gets changed/updated.

**Comment by frozenpandaman** [comment] 2016-03-18 11:42
@saucytomato @protomorph Update: Editing/updating post images gives the error I showed in #1043. Updating a post text field returns no error but fails to update as I said in my previous comment.

**Comment by protomorph** [comment] 2016-03-27 12:06
@saucytomato @frozenpandaman I think I may have found a fix for site variables not updating, open `anchor/routes/variables.php` and on line 122 change:
`Query::table(Base::table('meta'))->where('key', '=', $key)->update($input);`
to
`Query::table(Base::table('meta'))->where('key', '=', $input['key'])->update($input);`.
Let me know if that works for you.

**Comment by saucytomato** [comment] 2016-03-27 19:21
Thanks @protomorph . Works fine

**Comment by protomorph** [comment] 2016-03-27 20:11
excellent

**Comment by frozenpandaman** [comment] 2016-03-29 14:24
Hmm, still not working for me @protomorph. I made the change to line 122 in variables.php along with your earlier suggested changes of commenting out the else case on line 157 of posts.php. I change the time for a post (set to Draft) and click on save, but when clicking refresh it just changes to the current date/time of the system.

**Comment by protomorph** [comment] 2016-03-29 14:40
@frozenpandaman what version of anchor are you using?

**Comment by frozenpandaman** [comment] 2016-03-29 16:53
@protomorph 0.12.1

**Comment by protomorph** [comment] 2016-03-29 17:12
@frozenpandaman OK, can you try changing the date, go to the posts listings page, then go to post you just edited and see if it's the date you updated too.

**Comment by frozenpandaman** [comment] 2016-04-04 15:32
@protomorph The date never changes.

I try to change a date (e.g. the year to 2026) and upon refresh it simply stays as 2016, with the time updating to the current time. The same date/time is listed on the post listings page and is the table row entry for that post.

**Comment by CraigChilds94** [comment] 2016-06-18 15:03
This issue is now fixed.

**Closed by CraigChilds94** 2016-06-18 15:03 UTC
Labels: Bug, Medium Priority, Unconfirmed
