### ISSUE TITLE
Can't update custom fields in clean 0.12.1

### ISSUE THREAD

**Issue by xadz** [anchorcms/anchor-cms#1118] opened 2016-07-01 00:27 UTC
### Summary

Creating a custom field in the admin works fine, but you can not save the edit screen for an existing custom field.
### Expected Behaviour
- Create a custom field, edit an existing custom field and press save.
### Actual Behaviour
- Error occurs:

htmlspecialchars() expects parameter 1 to be string, array given
The error has been logged in /anchor/errors.log
Uncaught Exception

htmlspecialchars() expects parameter 1 to be string, array given

Origin

system/helpers.php on line 83

Trace
#0 [internal function]: System\Error::native(2, 'htmlspecialchar...', '/nfs/c11/h05/mn...', 83, Array)
#1 /nfs/c11/h05/mnt/206402/domains/adamgreenough.com/html/system/helpers.php(83): htmlspecialchars(Array, 3, 'UTF-8', false)
#2 /nfs/c11/h05/mnt/206402/domains/adamgreenough.com/html/system/helpers.php(90): e(Array, 3)
#3 /nfs/c11/h05/mnt/206402/domains/adamgreenough.com/html/anchor/routes/fields.php(136): eq(Array)
#4 [internal function]: {closure}('3')
#5 /nfs/c11/h05/mnt/206402/domains/adamgreenough.com/html/system/route.php(152): call_user_func_array(Object(Closure), Array)
#6 /nfs/c11/h05/mnt/206402/domains/adamgreenough.com/html/system/router.php(152): System\Route->run()
#7 /nfs/c11/h05/mnt/206402/domains/adamgreenough.com/html/system/start.php(46): System\Router->dispatch()
#8 /nfs/c11/h05/mnt/206402/domains/adamgreenough.com/html/index.php(35): require('/nfs/c11/h05/mn...')
#9 {main}
### Context details (if applicable)
- Anchor version: 0.12.1
- Server setup: MediaTemple Grid
- URL adamgreenough.com

**Comment by Gerrit0** [comment] 2016-07-01 02:45
Fixing the exception is easily done.

In `anchor/routes/fields.php` change

```PHP
foreach ($input as $key => &$value) {
    $value = eq($value);
}
```

at line 135 to

```PHP
array_walk_recursive($input, function(&$value) {
    $value = eq($value);
});
```

This doesn't fully fix the problem, however... and I'm having no luck getting the update statement to work correctly (it seems to be missing the `value` from the submitted post request, but, I can't even seem to figure out how to get this working correctly tonight. Tomorrow perhaps.)

Perhaps one of the team members who is more familiar with how the database update system works can offer a hand here.

**Comment by TheBrenny** [comment] 2016-07-04 00:44
Great catch! There should probably be a check in both the `e()` and `eq()`
methods that recursively calls itself if the found parameter is an array.
Might be able to look at this when I get back at the end of the week.

**Comment by jamestaylr** [comment] 2016-07-16 17:21
+1 I'm also experiencing this. After doing some random testing with this, I can confirm that the change @Gerrit0 suggested appears to work.

**Comment by TheBrenny** [comment] 2016-08-06 15:31
After a quick flick back, I can safely say that this has been reported before (#1068) and has been fixed (6eb3ff5). In order to get the patch, you need to make sure you have the Github version of AnchorCMS. If everything's okay, this'll get closed, otherwise this'll get closed in ~1 week.

**Comment by dval** [comment] 2018-01-23 12:45
line 126 of /anchor/routes/variables.php
`Query::table(Base::table('meta'))->where('key', '=', $key)->update($input);`

works if you change it to
`Query::table(Base::table('meta'))->where('key', '=', $input['key'])->update($input);`

The var `$key` litterally returns the string "value". Unless you name your custom field "value", it never gets updated. Using the resulting $input'value'] provides the correct field name, and the update will happen.   

I never received the exception that @xadz mentions, so assuming that is patched already.

**Comment by TheBrenny** [comment] 2019-01-26 12:15
Closing because we're well past that one week I said.

**Closed by TheBrenny** 2019-01-26 12:15 UTC
